CREATE VIEW dbo.vw_ActiveMigrateVMRequests
AS
SELECT [ID]
      ,[RequestName]
      ,[RequestDescription]
      ,[ParentAppName]
      ,[ParentAppID]
      ,[RequestType]
      ,[TargetServiceProviderType]
      ,[TargetLocation]
      ,[TargetLocationType]
      ,[TargetAccount]
      ,[TargetAccountType]
      ,[TargetAccountCreds]
      ,[VmSize]
      ,[TagData]
      ,[Config]
      ,[TargetVmName]
      ,[SourceServerName]
      ,[SourceVhdFilesCSV]
      ,[WhoRequested]
      ,[WhenRequested]
      ,[ExceptionMessage]
      ,[LastStatusUpdate]
      ,[StatusCode]
      ,[StatusMessage]
      ,[AftsID]
      ,[Active]
      ,[TargetServicename]
      ,[ServiceProviderStatusCheckTag]
      ,[TagID]
      ,[ServiceProviderAccountID]
      ,[OverwriteExisting]
      ,[CurrentStateStartTime]
      ,[CurrentStateTryCount]
      ,[Warnings]
      ,[ValidationResults]
      ,[SourceServerRegion]
      ,[ExceptionTypeCode]
      ,[LastState]
      ,[ServiceProviderResourceGroup]
  FROM [dbo].[VmDeploymentRequests]
  WHERE RequestType = 'MigrateVM' AND StatusCode NOT IN ('Complete', 'Exception', 'Rejected')