//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace CMP.Setup.SetupFramework
{
    using System.Xml.Serialization;
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class InstallItems {
        
        private InstallItemsInstallDataItem[] installDataItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstallDataItem")]
        public InstallItemsInstallDataItem[] InstallDataItem {
            get {
                return this.installDataItemField;
            }
            set {
                this.installDataItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstallItemsInstallDataItem {

        private InstallItemsInstallDataItemPreProcessing preProcessingField;
        
        private InstallItemsInstallDataItemPostProcessing postProcessingField;

        private InstallItemsInstallDataItemCustomAction customActionField;

        private InstallItemsInstallDataItemPrereq prereqField;
        
        private string[] dependencyField;
        
        private string controlTitleField;
        
        private string displayTitleField;
        
        private string installTypeField;
        
        private string itemWeAreInstallingField;
        
        private string fullPathToLaunchField;
        
        private string argumentsField;
        
        private string logFileField;
        
        private string productCodeField;
        
        private double timeField;
        
        private int successValueField;

        private ParentItemType parentItem;

        private string parentItemDisplayText;
        
        /// <remarks/>
        public InstallItemsInstallDataItemPreProcessing PreProcessing {
            get {
                return this.preProcessingField;
            }
            set {
                this.preProcessingField = value;
            }
        }

        /// <remarks/>
        public InstallItemsInstallDataItemCustomAction CustomAction
        {
            get
            {
                return this.customActionField;
            }
            set
            {
                this.customActionField = value;
            }
        }

        /// <remarks/>
        public InstallItemsInstallDataItemPostProcessing PostProcessing {
            get {
                return this.postProcessingField;
            }
            set {
                this.postProcessingField = value;
            }
        }
        
        /// <remarks/>
        public InstallItemsInstallDataItemPrereq Prereq {
            get {
                return this.prereqField;
            }
            set {
                this.prereqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dependency")]
        public string[] Dependency {
            get {
                return this.dependencyField;
            }
            set {
                this.dependencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ControlTitle {
            get {
                return this.controlTitleField;
            }
            set {
                this.controlTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayTitle {
            get {
                return this.displayTitleField;
            }
            set {
                this.displayTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InstallType {
            get {
                return this.installTypeField;
            }
            set {
                this.installTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemWeAreInstalling {
            get {
                return this.itemWeAreInstallingField;
            }
            set {
                this.itemWeAreInstallingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullPathToLaunch {
            get {
                return this.fullPathToLaunchField;
            }
            set {
                this.fullPathToLaunchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LogFile {
            get {
                return this.logFileField;
            }
            set {
                this.logFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SuccessValue {
            get {
                return this.successValueField;
            }
            set {
                this.successValueField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ParentItemType ParentItem
        {
            get
            {
                return this.parentItem;
            }
            set
            {
                this.parentItem = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParentItemDisplayText
        {
            get
            {
                return this.parentItemDisplayText;
            }
            set
            {
                this.parentItemDisplayText = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstallItemsInstallDataItemPreProcessing {
        
        private string delegateIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DelegateId {
            get {
                return this.delegateIdField;
            }
            set {
                this.delegateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InstallItemsInstallDataItemCustomAction
    {

        private string delegateIdField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DelegateId
        {
            get
            {
                return this.delegateIdField;
            }
            set
            {
                this.delegateIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstallItemsInstallDataItemPostProcessing {
        
        private string delegateIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DelegateId {
            get {
                return this.delegateIdField;
            }
            set {
                this.delegateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class InstallItemsInstallDataItemPrereq {
        
        private string delegateIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DelegateId {
            get {
                return this.delegateIdField;
            }
            set {
                this.delegateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
