//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/30/2013 3:32:51 PM
namespace Microsoft.WindowsAzurePack.CmpWapExtension.CmpClient.CmpService
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            var resolvedType = this.DefaultResolveType(typeName, "CmpInterfaceModel.Models", "Microsoft.WindowsAzurePack.CmpWapExtension.CmpClient.CmpService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Microsoft.WindowsAzurePack.CmpWapExtension.CmpClient.CmpService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CmpInterfaceModel.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for VmDeployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<VmDeploymentRequest> VmDeployments
        {
            get
            {
                if ((this._VmDeployments == null))
                {
                    this._VmDeployments = base.CreateQuery<VmDeploymentRequest>("VmDeployments");
                }
                return this._VmDeployments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<VmDeploymentRequest> _VmDeployments;
        /// <summary>
        /// There are no comments for VmDeployments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVmDeployments(VmDeploymentRequest vmDeploymentRequest)
        {
            base.AddObject("VmDeployments", vmDeploymentRequest);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"CmpInterfaceModel.Models\" xmlns=\"http://schemas.microsoft.com/ado/200" +
                "9/11/edm\"><EntityType Name=\"VmDeploymentRequest\"><Key><PropertyRef Name=\"ID\" /><" +
                "/Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Req" +
                "uestName\" Type=\"Edm.String\" /><Property Name=\"RequestDescription\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"ParentAppName\" Type=\"Edm.String\" /><Property Name=\"ParentA" +
                "ppID\" Type=\"Edm.String\" /><Property Name=\"RequestType\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"TargetServiceProviderType\" Type=\"Edm.String\" /><Property Name=\"Target" +
                "ServiceName\" Type=\"Edm.String\" /><Property Name=\"TargetLocation\" Type=\"Edm.Strin" +
                "g\" /><Property Name=\"TargetLocationType\" Type=\"Edm.String\" /><Property Name=\"Tar" +
                "getAccount\" Type=\"Edm.String\" /><Property Name=\"TargetAccountType\" Type=\"Edm.Str" +
                "ing\" /><Property Name=\"TargetAccountCreds\" Type=\"Edm.String\" /><Property Name=\"V" +
                "mSize\" Type=\"Edm.String\" /><Property Name=\"TagData\" Type=\"Edm.String\" /><Propert" +
                "y Name=\"TagID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Config\" Type=" +
                "\"Edm.String\" /><Property Name=\"TargetVmName\" Type=\"Edm.String\" /><Property Name=" +
                "\"SourceServerName\" Type=\"Edm.String\" /><Property Name=\"SourceVhdFilesCSV\" Type=\"" +
                "Edm.String\" /><Property Name=\"WhoRequested\" Type=\"Edm.String\" /><Property Name=\"" +
                "WhenRequested\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"ExceptionM" +
                "essage\" Type=\"Edm.String\" /><Property Name=\"LastStatusUpdate\" Type=\"Edm.DateTime" +
                "\" Nullable=\"false\" /><Property Name=\"Status\" Type=\"Edm.String\" /><Property Name=" +
                "\"StatusMessage\" Type=\"Edm.String\" /><Property Name=\"AftsID\" Type=\"Edm.Int32\" Nul" +
                "lable=\"false\" /><Property Name=\"Active\" Type=\"Edm.Boolean\" Nullable=\"false\" /></" +
                "EntityType></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas.microsoft." +
                "com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEntityContaine" +
                "r=\"true\"><EntitySet Name=\"VmDeployments\" EntityType=\"CmpInterfaceModel.Models.Vm" +
                "DeploymentRequest\" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>" +
                "";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                var edmxToParse = GetConcatenatedEdmxString();
                var reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for CmpInterfaceModel.Models.VmDeploymentRequest in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("VmDeployments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class VmDeploymentRequest : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VmDeploymentRequest object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="tagID">Initial value of TagID.</param>
        /// <param name="whenRequested">Initial value of WhenRequested.</param>
        /// <param name="lastStatusUpdate">Initial value of LastStatusUpdate.</param>
        /// <param name="aftsID">Initial value of AftsID.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static VmDeploymentRequest CreateVmDeploymentRequest(int ID, int tagID, global::System.DateTime whenRequested, global::System.DateTime lastStatusUpdate, int aftsID, bool active)
        {
            var vmDeploymentRequest = new VmDeploymentRequest();
            vmDeploymentRequest.ID = ID;
            vmDeploymentRequest.TagID = tagID;
            vmDeploymentRequest.WhenRequested = whenRequested;
            vmDeploymentRequest.LastStatusUpdate = lastStatusUpdate;
            vmDeploymentRequest.AftsID = aftsID;
            vmDeploymentRequest.Active = active;
            return vmDeploymentRequest;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property RequestName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequestName
        {
            get
            {
                return this._RequestName;
            }
            set
            {
                this.OnRequestNameChanging(value);
                this._RequestName = value;
                this.OnRequestNameChanged();
                this.OnPropertyChanged("RequestName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequestName;
        partial void OnRequestNameChanging(string value);
        partial void OnRequestNameChanged();
        /// <summary>
        /// There are no comments for Property RequestDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequestDescription
        {
            get
            {
                return this._RequestDescription;
            }
            set
            {
                this.OnRequestDescriptionChanging(value);
                this._RequestDescription = value;
                this.OnRequestDescriptionChanged();
                this.OnPropertyChanged("RequestDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequestDescription;
        partial void OnRequestDescriptionChanging(string value);
        partial void OnRequestDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ParentAppName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ParentAppName
        {
            get
            {
                return this._ParentAppName;
            }
            set
            {
                this.OnParentAppNameChanging(value);
                this._ParentAppName = value;
                this.OnParentAppNameChanged();
                this.OnPropertyChanged("ParentAppName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ParentAppName;
        partial void OnParentAppNameChanging(string value);
        partial void OnParentAppNameChanged();
        /// <summary>
        /// There are no comments for Property ParentAppID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ParentAppID
        {
            get
            {
                return this._ParentAppID;
            }
            set
            {
                this.OnParentAppIDChanging(value);
                this._ParentAppID = value;
                this.OnParentAppIDChanged();
                this.OnPropertyChanged("ParentAppID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ParentAppID;
        partial void OnParentAppIDChanging(string value);
        partial void OnParentAppIDChanged();
        /// <summary>
        /// There are no comments for Property RequestType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RequestType
        {
            get
            {
                return this._RequestType;
            }
            set
            {
                this.OnRequestTypeChanging(value);
                this._RequestType = value;
                this.OnRequestTypeChanged();
                this.OnPropertyChanged("RequestType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RequestType;
        partial void OnRequestTypeChanging(string value);
        partial void OnRequestTypeChanged();
        /// <summary>
        /// There are no comments for Property TargetServiceProviderType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetServiceProviderType
        {
            get
            {
                return this._TargetServiceProviderType;
            }
            set
            {
                this.OnTargetServiceProviderTypeChanging(value);
                this._TargetServiceProviderType = value;
                this.OnTargetServiceProviderTypeChanged();
                this.OnPropertyChanged("TargetServiceProviderType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetServiceProviderType;
        partial void OnTargetServiceProviderTypeChanging(string value);
        partial void OnTargetServiceProviderTypeChanged();
        /// <summary>
        /// There are no comments for Property TargetServiceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetServiceName
        {
            get
            {
                return this._TargetServiceName;
            }
            set
            {
                this.OnTargetServiceNameChanging(value);
                this._TargetServiceName = value;
                this.OnTargetServiceNameChanged();
                this.OnPropertyChanged("TargetServiceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetServiceName;
        partial void OnTargetServiceNameChanging(string value);
        partial void OnTargetServiceNameChanged();
        /// <summary>
        /// There are no comments for Property TargetLocation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetLocation
        {
            get
            {
                return this._TargetLocation;
            }
            set
            {
                this.OnTargetLocationChanging(value);
                this._TargetLocation = value;
                this.OnTargetLocationChanged();
                this.OnPropertyChanged("TargetLocation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetLocation;
        partial void OnTargetLocationChanging(string value);
        partial void OnTargetLocationChanged();
        /// <summary>
        /// There are no comments for Property TargetLocationType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetLocationType
        {
            get
            {
                return this._TargetLocationType;
            }
            set
            {
                this.OnTargetLocationTypeChanging(value);
                this._TargetLocationType = value;
                this.OnTargetLocationTypeChanged();
                this.OnPropertyChanged("TargetLocationType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetLocationType;
        partial void OnTargetLocationTypeChanging(string value);
        partial void OnTargetLocationTypeChanged();
        /// <summary>
        /// There are no comments for Property TargetAccount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetAccount
        {
            get
            {
                return this._TargetAccount;
            }
            set
            {
                this.OnTargetAccountChanging(value);
                this._TargetAccount = value;
                this.OnTargetAccountChanged();
                this.OnPropertyChanged("TargetAccount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetAccount;
        partial void OnTargetAccountChanging(string value);
        partial void OnTargetAccountChanged();
        /// <summary>
        /// There are no comments for Property TargetAccountType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetAccountType
        {
            get
            {
                return this._TargetAccountType;
            }
            set
            {
                this.OnTargetAccountTypeChanging(value);
                this._TargetAccountType = value;
                this.OnTargetAccountTypeChanged();
                this.OnPropertyChanged("TargetAccountType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetAccountType;
        partial void OnTargetAccountTypeChanging(string value);
        partial void OnTargetAccountTypeChanged();
        /// <summary>
        /// There are no comments for Property TargetAccountCreds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetAccountCreds
        {
            get
            {
                return this._TargetAccountCreds;
            }
            set
            {
                this.OnTargetAccountCredsChanging(value);
                this._TargetAccountCreds = value;
                this.OnTargetAccountCredsChanged();
                this.OnPropertyChanged("TargetAccountCreds");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetAccountCreds;
        partial void OnTargetAccountCredsChanging(string value);
        partial void OnTargetAccountCredsChanged();
        /// <summary>
        /// There are no comments for Property VmSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VmSize
        {
            get
            {
                return this._VmSize;
            }
            set
            {
                this.OnVmSizeChanging(value);
                this._VmSize = value;
                this.OnVmSizeChanged();
                this.OnPropertyChanged("VmSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VmSize;
        partial void OnVmSizeChanging(string value);
        partial void OnVmSizeChanged();
        /// <summary>
        /// There are no comments for Property TagData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TagData
        {
            get
            {
                return this._TagData;
            }
            set
            {
                this.OnTagDataChanging(value);
                this._TagData = value;
                this.OnTagDataChanged();
                this.OnPropertyChanged("TagData");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TagData;
        partial void OnTagDataChanging(string value);
        partial void OnTagDataChanged();
        /// <summary>
        /// There are no comments for Property TagID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TagID
        {
            get
            {
                return this._TagID;
            }
            set
            {
                this.OnTagIDChanging(value);
                this._TagID = value;
                this.OnTagIDChanged();
                this.OnPropertyChanged("TagID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TagID;
        partial void OnTagIDChanging(int value);
        partial void OnTagIDChanged();
        /// <summary>
        /// There are no comments for Property Config in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Config
        {
            get
            {
                return this._Config;
            }
            set
            {
                this.OnConfigChanging(value);
                this._Config = value;
                this.OnConfigChanged();
                this.OnPropertyChanged("Config");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Config;
        partial void OnConfigChanging(string value);
        partial void OnConfigChanged();
        /// <summary>
        /// There are no comments for Property TargetVmName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TargetVmName
        {
            get
            {
                return this._TargetVmName;
            }
            set
            {
                this.OnTargetVmNameChanging(value);
                this._TargetVmName = value;
                this.OnTargetVmNameChanged();
                this.OnPropertyChanged("TargetVmName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TargetVmName;
        partial void OnTargetVmNameChanging(string value);
        partial void OnTargetVmNameChanged();
        /// <summary>
        /// There are no comments for Property SourceServerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceServerName
        {
            get
            {
                return this._SourceServerName;
            }
            set
            {
                this.OnSourceServerNameChanging(value);
                this._SourceServerName = value;
                this.OnSourceServerNameChanged();
                this.OnPropertyChanged("SourceServerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceServerName;
        partial void OnSourceServerNameChanging(string value);
        partial void OnSourceServerNameChanged();
        /// <summary>
        /// There are no comments for Property SourceVhdFilesCSV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceVhdFilesCSV
        {
            get
            {
                return this._SourceVhdFilesCSV;
            }
            set
            {
                this.OnSourceVhdFilesCSVChanging(value);
                this._SourceVhdFilesCSV = value;
                this.OnSourceVhdFilesCSVChanged();
                this.OnPropertyChanged("SourceVhdFilesCSV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceVhdFilesCSV;
        partial void OnSourceVhdFilesCSVChanging(string value);
        partial void OnSourceVhdFilesCSVChanged();
        /// <summary>
        /// There are no comments for Property WhoRequested in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WhoRequested
        {
            get
            {
                return this._WhoRequested;
            }
            set
            {
                this.OnWhoRequestedChanging(value);
                this._WhoRequested = value;
                this.OnWhoRequestedChanged();
                this.OnPropertyChanged("WhoRequested");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WhoRequested;
        partial void OnWhoRequestedChanging(string value);
        partial void OnWhoRequestedChanged();
        /// <summary>
        /// There are no comments for Property WhenRequested in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime WhenRequested
        {
            get
            {
                return this._WhenRequested;
            }
            set
            {
                this.OnWhenRequestedChanging(value);
                this._WhenRequested = value;
                this.OnWhenRequestedChanged();
                this.OnPropertyChanged("WhenRequested");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _WhenRequested;
        partial void OnWhenRequestedChanging(global::System.DateTime value);
        partial void OnWhenRequestedChanged();
        /// <summary>
        /// There are no comments for Property ExceptionMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ExceptionMessage
        {
            get
            {
                return this._ExceptionMessage;
            }
            set
            {
                this.OnExceptionMessageChanging(value);
                this._ExceptionMessage = value;
                this.OnExceptionMessageChanged();
                this.OnPropertyChanged("ExceptionMessage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ExceptionMessage;
        partial void OnExceptionMessageChanging(string value);
        partial void OnExceptionMessageChanged();
        /// <summary>
        /// There are no comments for Property LastStatusUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastStatusUpdate
        {
            get
            {
                return this._LastStatusUpdate;
            }
            set
            {
                this.OnLastStatusUpdateChanging(value);
                this._LastStatusUpdate = value;
                this.OnLastStatusUpdateChanged();
                this.OnPropertyChanged("LastStatusUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastStatusUpdate;
        partial void OnLastStatusUpdateChanging(global::System.DateTime value);
        partial void OnLastStatusUpdateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property StatusMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StatusMessage
        {
            get
            {
                return this._StatusMessage;
            }
            set
            {
                this.OnStatusMessageChanging(value);
                this._StatusMessage = value;
                this.OnStatusMessageChanged();
                this.OnPropertyChanged("StatusMessage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StatusMessage;
        partial void OnStatusMessageChanging(string value);
        partial void OnStatusMessageChanged();
        /// <summary>
        /// There are no comments for Property AftsID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AftsID
        {
            get
            {
                return this._AftsID;
            }
            set
            {
                this.OnAftsIDChanging(value);
                this._AftsID = value;
                this.OnAftsIDChanged();
                this.OnPropertyChanged("AftsID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AftsID;
        partial void OnAftsIDChanging(int value);
        partial void OnAftsIDChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
