//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP.Setup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMP.Setup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes actions initiated by users through the web extention portal.
        /// </summary>
        internal static string EngineServiceDescription {
            get {
                return ResourceManager.GetString("EngineServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMP Worker Service.
        /// </summary>
        internal static string EngineServiceDisplayName {
            get {
                return ResourceManager.GetString("EngineServiceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid prerequisite result output file.
        /// </summary>
        internal static string errInvalidPrereqResultFile {
            get {
                return ResourceManager.GetString("errInvalidPrereqResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenCheck {
            get {
                object obj = ResourceManager.GetObject("GreenCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information_32 {
            get {
                object obj = ResourceManager.GetObject("Information_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up database.
        /// </summary>
        internal static string InstallItemBackingupVMM2008R2SP1database {
            get {
                return ResourceManager.GetString("InstallItemBackingupVMM2008R2SP1database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying registry keys.
        /// </summary>
        internal static string InstallItemCopyingregistrykeys {
            get {
                return ResourceManager.GetString("InstallItemCopyingregistrykeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Configuration.
        /// </summary>
        internal static string InstallItemFinalConfiguration {
            get {
                return ResourceManager.GetString("InstallItemFinalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB874893.
        /// </summary>
        internal static string InstallItemKB874893 {
            get {
                return ResourceManager.GetString("InstallItemKB874893", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server 2014 Management Objects.
        /// </summary>
        internal static string InstallItemMicrosoftSQLServer2014ManagementObjects {
            get {
                return ResourceManager.GetString("InstallItemMicrosoftSQLServer2014ManagementObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server 2014 Transact-SQL ScriptDom.
        /// </summary>
        internal static string InstallItemMicrosoftSQLServer2014TransactSQLScriptDom {
            get {
                return ResourceManager.GetString("InstallItemMicrosoftSQLServer2014TransactSQLScriptDom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server Data-Tier Application Framework (x64).
        /// </summary>
        internal static string InstallItemMicrosoftSQLServerDataTierApplicationFrameworkx64 {
            get {
                return ResourceManager.GetString("InstallItemMicrosoftSQLServerDataTierApplicationFrameworkx64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Storage Management Service.
        /// </summary>
        internal static string InstallItemMicrosoftStorageManagementService {
            get {
                return ResourceManager.GetString("InstallItemMicrosoftStorageManagementService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft System CLR Types For SQL Server 2014.
        /// </summary>
        internal static string InstallItemMicrosoftSystemCLRTypesForSQLServer2014 {
            get {
                return ResourceManager.GetString("InstallItemMicrosoftSystemCLRTypesForSQLServer2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for Upgrade.
        /// </summary>
        internal static string InstallItemPreparingforUpgrade {
            get {
                return ResourceManager.GetString("InstallItemPreparingforUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Existing Installation.
        /// </summary>
        internal static string InstallItemRemovingExistingInstallation {
            get {
                return ResourceManager.GetString("InstallItemRemovingExistingInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InstallItems&gt;
        ///&lt;!--
        ///&lt;InstallDataItem ControlTitle=&quot;&quot; 
        ///                                //This is a unique ID used to identify this DataItem
        ///                 DisplayTitle=&quot;&quot; 
        ///                                //This is the title for the data item.
        ///                 InstallType=&quot;&quot; 
        ///                                //This is the type of the install.
        ///                                //Valid types are:
        ///                                //  ExecutableInstall
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallItems {
            get {
                return ResourceManager.GetString("InstallItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping services.
        /// </summary>
        internal static string InstallItemStoppingservices {
            get {
                return ResourceManager.GetString("InstallItemStoppingservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Pages&gt;
        ///  &lt;Page Id =&quot;SwitchPage&quot; Implementation=&quot;CMP.Setup.SwitchPage&quot;&gt;
        ///    &lt;PreviousPage delegateId=&quot;CMP.Setup.CustomDelegates.NullPageHandler&quot;&gt;&lt;/PreviousPage&gt;
        ///    &lt;NextPage delegateId=&quot;CMP.Setup.CustomDelegates.ForwardFromSwitchPageHandler&quot;&gt;ARPStartPageSwitch,InitialInstallStartPageSwitch&lt;/NextPage&gt;
        ///    &lt;HelpPage&gt;{D035D6FD-0E32-463B-8C45-34502ECBC611}&lt;/HelpPage&gt;
        ///  &lt;/Page&gt;
        ///
        ///  &lt;!--Start Pages in more than one flow--&gt;
        ///  &lt;Page Id =&quot;BlockPage&quot; Implementation=&quot;CM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Retry_16 {
            get {
                object obj = ResourceManager.GetObject("Retry_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightGreenArrow {
            get {
                object obj = ResourceManager.GetObject("RightGreenArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallRedX {
            get {
                object obj = ResourceManager.GetObject("smallRedX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallSuccessCheck {
            get {
                object obj = ResourceManager.GetObject("smallSuccessCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
