CREATE TABLE [dbo].[VmDeploymentRequests] (
    [ID]                            INT            NOT NULL,
    [RequestName]                   VARCHAR (50)   NULL,
    [RequestDescription]            VARCHAR (1024) NULL,
    [ParentAppName]                 VARCHAR (100)  NULL,
    [ParentAppID]                   VARCHAR (50)   NULL,
    [RequestType]                   VARCHAR (50)   NULL,
    [TargetServiceProviderType]     VARCHAR (50)   NULL,
    [TargetLocation]                VARCHAR (50)   NULL,
    [TargetLocationType]            VARCHAR (50)   NULL,
    [TargetAccount]                 VARCHAR (100)  NULL,
    [TargetAccountType]             VARCHAR (50)   NULL,
    [TargetAccountCreds]            VARCHAR (4096) NULL,
    [VmSize]                        VARCHAR (50)   NULL,
    [TagData]                       VARCHAR (MAX)  NULL,
    [Config]                        VARCHAR (MAX)  NULL,
    [TargetVmName]                  VARCHAR (256)  NULL,
    [SourceServerName]              VARCHAR (256)  NULL,
    [SourceVhdFilesCSV]             VARCHAR (MAX)  NULL,
    [WhoRequested]                  VARCHAR (100)  NULL,
    [WhenRequested]                 DATETIME       NULL,
    [ExceptionMessage]              VARCHAR (MAX)  NULL,
    [LastStatusUpdate]              DATETIME       NULL,
    [StatusCode]                    VARCHAR (50)   NULL,
    [StatusMessage]                 VARCHAR (4096) NULL,
    [AftsID]                        INT            NULL,
    [Active]                        BIT            NULL,
    [TargetServicename]             VARCHAR (100)  NULL,
    [ServiceProviderStatusCheckTag] VARCHAR (MAX)  NULL,
    [TagID]                         INT            NULL,
    [ServiceProviderAccountID]      INT            NULL,
    [OverwriteExisting]             BIT            NULL,
    [CurrentStateStartTime]         DATETIME       NULL,
    [CurrentStateTryCount]          INT            NULL,
    [Warnings]                      VARCHAR (MAX)  NULL,
    [ValidationResults]             VARCHAR (MAX)  NULL,
    [SourceServerRegion]            VARCHAR (100)  NULL,
    [ExceptionTypeCode]             VARCHAR (50)   NULL,
    [LastState]                     VARCHAR (50)   NULL,
    [ServiceProviderResourceGroup]  VARCHAR (50)   NULL,
    [ConfigOriginal]                VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_VmDeploymentRequests_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

